import asyncio
import random

from better_profanity import profanity
from discord import app_commands
from discord.ext import commands
import discord

from ai.quest_generator import generate_quest, continue_quest
from database.player import (
    get_player_profile,
    update_player_location,
    apply_lead_rewards,
    add_coins,
    add_pokemon_to_box,
)
from pokemon.data import stored_name_sprite_url
from pokemon.economy import roll_quest_coin_reward
from pokemon.growth import roll_exp_reward, roll_friendship_reward
from pokemon.legendary_quest import roll_for_legendary_encounter, legendary_join_text


# How many follow-up steps a quest chain gets after the first one,
# picked once when the quest starts. This is decided here, by plain
# Python, not by the AI - the same "engine controls structure, AI
# controls content" split used everywhere else in the project (see
# pokemon/encounters.py). Without a fixed limit like this, there'd be
# nothing stopping a quest chain from running forever.
MIN_QUEST_STEPS = 2
MAX_QUEST_STEPS = 3

# /explore deliberately accepts ANY typed location, not just real
# Pokemon places (see claude/design-decisions.md for the reasoning) -
# that's a deliberate choice to show the AI module generalising to
# arbitrary input, not an oversight. But "any input" still needs two
# basic guardrails before it's dropped straight into an AI prompt:
#
# 1. A length cap - real Pokemon locations are always short
#    ("Viridian Forest", "Cerulean Cave"), so this is generous headroom
#    for anything reasonable, while stopping someone from pasting an
#    essay-length wall of text into the prompt.
MAX_LOCATION_LENGTH = 60


def _rejection_reason_for(location: str) -> str | None:
    """
    Check a (already-stripped) player-typed location against both
    guardrails, and return an error message to show them if it fails
    either one - or None if the location is fine to use.

    Pulled out into its own plain function (rather than living inline
    inside explore() below) purely so it can be unit tested directly -
    see tests/test_explore.py - without needing a fake Discord context
    or an actual bot connection.

    Strips whitespace itself rather than trusting the caller to have
    already done it - explore() below does still strip before calling
    this (since it reuses the stripped result afterwards), but this
    function checks its own input so it behaves correctly even if
    called from somewhere else later that forgets to.
    """
    location = location.strip()

    if not location:
        return "❌ You need to type somewhere to explore, e.g. `;explore Viridian Forest`."

    if len(location) > MAX_LOCATION_LENGTH:
        return (
            f"❌ That location name is too long (max {MAX_LOCATION_LENGTH} characters) - "
            "try something shorter, like `Viridian Forest`."
        )

    if profanity.contains_profanity(location):
        # better-profanity checks the text against its own built-in
        # word list - see the "how it works" explanation given
        # alongside this change for what that actually means.
        return "❌ That doesn't look like an appropriate location - try something else!"

    return None


def _build_quest_embed(location: str, step_data: dict, is_final: bool, author) -> discord.Embed:
    """
    Build the embed shown for one step of a quest (the first step or
    any later fork). Shared by the initial /explore command and every
    button callback below, so the two don't drift out of sync with
    each other's formatting.
    """
    title = step_data.get("title")
    embed = discord.Embed(
        title=f"🌎 {author.display_name} is exploring {location}",
        description=f"**{title}**\n\n{step_data['scene']}" if title else step_data["scene"],
        colour=discord.Colour.green(),
    )

    if step_data.get("npc"):
        embed.add_field(name="👤 NPC", value=step_data["npc"], inline=False)

    embed.add_field(
        name="🏁 Outcome" if is_final else "🎯 Objective",
        value=step_data.get("objective", ""),
        inline=False,
    )

    choices = step_data.get("choices") or []
    if choices and not is_final:
        choices_text = "\n".join(f"{i + 1}. {choice}" for i, choice in enumerate(choices))
        embed.add_field(name="🧭 Choices", value=choices_text, inline=False)
        embed.set_footer(
            text="This quest was generated by AI. Pick a button below to continue."
        )
    else:
        embed.set_footer(
            text="Quest complete! Run /explore again to start a new one."
        )

    return embed


def _apply_rewards_and_describe(discord_user_id: int) -> str | None:
    """
    Called exactly once, the moment a quest chain reaches its final
    step - rolls EXP, friendship (pokemon/growth.py), and coins
    (pokemon/economy.py), awarding the EXP/friendship to the player's
    LEAD team Pokémon (see apply_lead_rewards()'s docstring for why the
    lead, specifically, is the one rewarded) and the coins straight to
    the player's balance, the same way a successful /catch does.

    Returns a ready-to-display summary line for the quest's final
    embed, or None if the player's team was somehow empty (shouldn't
    normally happen, since a team always starts with one Pokémon, but
    handled rather than crashing just in case) - no coins are awarded
    in that case either, so a quest with no Pokémon to reward doesn't
    still quietly pay out.
    """
    exp_gained = roll_exp_reward()
    friendship_gained = roll_friendship_reward()

    result = apply_lead_rewards(discord_user_id, exp_gained, friendship_gained)
    if result is None:
        return None

    coins_gained = roll_quest_coin_reward()
    new_balance = add_coins(discord_user_id, coins_gained)

    text = (
        f"🐾 **{result['name']}** gained **{exp_gained} EXP** and **+{friendship_gained} friendship**"
    )
    if result["leveled_up"]:
        text += f" - and levelled up to **Level {result['level']}**! 🎉"
    else:
        text += f" (now Level {result['level']})."
    text += f"\n🪙 +{coins_gained:,} coins - balance: {new_balance:,}"

    return text


def _roll_legendary_bonus(discord_user_id: int, player_display_name: str) -> dict | None:
    """
    Called once, right after a quest's normal rewards are applied, to
    check for the rare "a legendary reveals itself" bonus (see
    pokemon/legendary_quest.py). This only ever adds ON TOP of the
    normal reward - if the roll doesn't hit, the quest still paid out
    EXP, friendship, and coins as usual via _apply_rewards_and_describe()
    above.

    Returns a dict with the species name, its ready-to-display
    flavour text, and its sprite URL (for the standalone embed's
    image - see _build_legendary_embed() below), or None if nothing
    happened this time.
    """
    species_name = roll_for_legendary_encounter()
    if species_name is None:
        return None

    # Goes straight to the box, the same way the owner-only ;spawn
    # command does (see commands/dev.py) - not through
    # add_caught_pokemon(), since this isn't a catch and shouldn't be
    # able to bump something else out of a full team.
    add_pokemon_to_box(discord_user_id, species_name)

    return {
        "species": species_name,
        "text": legendary_join_text(species_name, player_display_name),
        "sprite_url": stored_name_sprite_url(species_name),
    }


def _build_legendary_embed(legendary: dict) -> discord.Embed:
    """
    Build the standalone embed shown when the legendary quest bonus
    hits (see _roll_legendary_bonus() above).

    This is deliberately its OWN embed, sent alongside the quest's
    embed rather than as an extra field tacked onto it. Discord only
    renders an embed's set_thumbnail() image small, in the corner -
    set_image() is the one that renders big, but only one image (of
    either kind) is allowed per embed, and the quest embed already
    uses its space for the scene text and rewards. A second, dedicated
    embed is the only way to get a full-size Ho-Oh/Lugia picture,
    which is the whole point - a tiny corner icon undersold what's
    meant to be an exciting, rare moment.
    """
    embed = discord.Embed(
        title="🌟 A Mystical Presence...",
        description=legendary["text"],
        colour=discord.Colour.gold(),
    )
    if legendary["sprite_url"]:
        embed.set_image(url=legendary["sprite_url"])
    return embed


class QuestChoiceButton(discord.ui.Button):
    """One button representing a single choice from the current quest step."""

    def __init__(self, index: int, choice_text: str):
        # Discord button labels are capped at 80 characters - truncate
        # long AI-generated choice text rather than letting Discord
        # reject the whole message over one oversized label.
        label = choice_text if len(choice_text) <= 80 else choice_text[:77] + "..."
        super().__init__(label=f"{index}. {label}", style=discord.ButtonStyle.primary)
        self.choice_text = choice_text

    async def callback(self, interaction: discord.Interaction):
        view: QuestView = self.view

        # Only the player who ran /explore can click their own quest's
        # buttons - otherwise anyone in the channel could hijack
        # someone else's story.
        if interaction.user.id != view.author_id:
            await interaction.response.send_message(
                embed=discord.Embed(
                    description="This isn't your quest, run your own /explore!",
                    colour=discord.Colour.red(),
                ),
                ephemeral=True,
            )
            return

        # Disable every button immediately, before the (slow) AI call,
        # so a second click while the next step is still generating
        # can't fire this callback twice for the same step.
        for child in view.children:
            child.disabled = True
        await interaction.response.edit_message(view=view)

        is_final = view.step >= view.target_steps

        step_data = await asyncio.to_thread(
            continue_quest,
            location=view.location,
            player_level=view.player_level,
            team=view.team,
            vibe=view.vibe,
            sound=view.sound,
            history=view.history,
            choice_taken=self.choice_text,
            is_final=is_final,
        )

        new_history = view.history + [step_data.get("scene", "")]
        choices = step_data.get("choices") or []
        # Even if the model didn't respect is_final and returned
        # choices anyway, MAX_QUEST_STEPS is enforced here in code -
        # this is the deterministic limit the docstring in
        # continue_quest() promises.
        is_final = is_final or not choices

        embed = _build_quest_embed(view.location, step_data, is_final, interaction.user)

        if is_final:
            rewards_text = _apply_rewards_and_describe(interaction.user.id)
            if rewards_text:
                embed.add_field(name="✨ Rewards", value=rewards_text, inline=False)

            # Sent as a SECOND embed (not a field on the one above) so
            # its sprite can be shown full-size - see
            # _build_legendary_embed()'s docstring for why.
            embeds = [embed]
            legendary = _roll_legendary_bonus(interaction.user.id, interaction.user.display_name)
            if legendary:
                embeds.append(_build_legendary_embed(legendary))

            await interaction.edit_original_response(embeds=embeds, view=None)
            return

        next_view = QuestView(
            author_id=view.author_id,
            location=view.location,
            player_level=view.player_level,
            team=view.team,
            vibe=view.vibe,
            sound=view.sound,
            history=new_history,
            step=view.step + 1,
            target_steps=view.target_steps,
            choices=choices,
        )
        await interaction.edit_original_response(embed=embed, view=next_view)


class QuestView(discord.ui.View):
    """
    The set of choice buttons shown under one quest step.

    A fresh QuestView is built for every step (see QuestChoiceButton
    above), rather than reusing one View and swapping its buttons -
    that keeps each step's state (history, step count) naturally tied
    to the message it's attached to.
    """

    def __init__(
        self,
        *,
        author_id: int,
        location: str,
        player_level: int,
        team: list[dict],
        vibe: str,
        sound: str,
        history: list[str],
        step: int,
        target_steps: int,
        choices: list[str],
    ):
        # timeout=120: if nobody clicks within 2 minutes, on_timeout()
        # below disables the buttons so the quest doesn't sit there
        # forever looking clickable when it no longer works.
        super().__init__(timeout=120)

        self.author_id = author_id
        self.location = location
        self.player_level = player_level
        self.team = team
        self.vibe = vibe
        self.sound = sound
        self.history = history
        self.step = step
        self.target_steps = target_steps

        # message is set by the caller right after sending, so
        # on_timeout() has something to edit. See explore.py below.
        self.message: discord.Message | None = None

        for i, choice_text in enumerate(choices[:3], start=1):
            self.add_item(QuestChoiceButton(i, choice_text))

    async def on_timeout(self):
        for child in self.children:
            child.disabled = True

        if self.message is not None:
            try:
                await self.message.edit(view=self)
            except discord.HTTPException:
                # The message may have been deleted, or we may have
                # lost permission to edit it - either way, there's
                # nothing more useful to do here.
                pass


def setup(bot: commands.Bot):

    @bot.hybrid_command(
        name="explore",
        description="Explore an area and generate an AI quest."
    )
    @app_commands.describe(
        location="Choose somewhere to explore, e.g. Viridian Forest"
    )
    async def explore(
        ctx: commands.Context,
        *,  # the * makes "location" keyword-only, which for the ;explore
            # prefix form means "everything typed after the command name"
            # is captured as one string (so multi-word locations like
            # "Viridian Forest" work without needing quotes). It has no
            # effect on the /explore slash-command form, which already
            # treats location as a single text option either way.
        location: str
    ):
        # location.strip() so "   " (spaces only) counts as empty too -
        # a bare ";explore" with nothing at all is already caught
        # earlier by discord.py itself (MissingRequiredArgument, see
        # bot.py's on_command_error), but that only checks that
        # SOMETHING was typed, not that it's non-blank.
        location = location.strip()

        # Checked BEFORE any slow work (the database call, the AI call)
        # happens - a rejected location shouldn't cost a wasted Ollama
        # request or even show the "Generating a quest..." message.
        rejection_reason = _rejection_reason_for(location)
        if rejection_reason is not None:
            # Every command's final output is an embed, for a
            # consistent look - _rejection_reason_for() itself still
            # just returns a plain string (see its own docstring for
            # why - so it stays trivially unit-testable), and it's only
            # wrapped in an embed here, right before it's sent.
            await ctx.send(embed=discord.Embed(
                description=rejection_reason,
                colour=discord.Colour.red(),
            ))
            return

        message = await ctx.send(
            f"Generating a quest for {ctx.author.mention}... ⏳"
        )

        player = get_player_profile(ctx.author.id)

        # Remember where this player last explored, so their profile
        # reflects it next time (and future features, like encounters,
        # can use it).
        update_player_location(ctx.author.id, location)

        # generate_quest() ends up calling requests.post(), which is a
        # BLOCKING call - it would otherwise freeze the bot's entire
        # event loop (including the heartbeat that keeps Discord from
        # thinking the bot has died) until Ollama responds.
        # asyncio.to_thread() runs it on a separate background thread
        # instead, so the rest of the bot stays responsive while we wait.
        quest, vibe, sound = await asyncio.to_thread(
            generate_quest,
            location=location,
            player_level=player["level"],
            team=player["team"]
        )

        # Pick how many steps this quest chain gets, once, here -
        # never re-picked mid-chain. MIN/MAX_QUEST_STEPS are the only
        # things controlling when a quest ends; the AI is never asked
        # to decide that for itself (see continue_quest()'s docstring).
        target_steps = random.randint(MIN_QUEST_STEPS, MAX_QUEST_STEPS)

        choices = quest.get("choices") or []
        is_final = target_steps <= 1 or not choices
        embed = _build_quest_embed(location, quest, is_final, ctx.author)

        legendary = None
        if is_final:
            view = None
            rewards_text = _apply_rewards_and_describe(ctx.author.id)
            if rewards_text:
                embed.add_field(name="✨ Rewards", value=rewards_text, inline=False)

            legendary = _roll_legendary_bonus(ctx.author.id, ctx.author.display_name)
        else:
            view = QuestView(
                author_id=ctx.author.id,
                location=location,
                player_level=player["level"],
                team=player["team"],
                vibe=vibe,
                sound=sound,
                history=[quest.get("scene", "")],
                step=1,
                target_steps=target_steps,
                choices=choices,
            )

        # Sent as a SECOND embed (not a field on the one above) so its
        # sprite can be shown full-size - see _build_legendary_embed()'s
        # docstring for why. embeds=[...] (rather than embed=) is used
        # even when there's only one, since a hybrid command's message
        # can't mix the "embed=" and "embeds=" kwargs across the two
        # branches above.
        embeds = [embed]
        if legendary:
            embeds.append(_build_legendary_embed(legendary))

        # message.edit() works the same way whether "message" came from
        # a slash-command response or a plain sent message, so this one
        # line covers both /explore and ;explore.
        await message.edit(
            content=f"{ctx.author.mention}, your quest is ready!",
            embeds=embeds,
            view=view,
        )

        if view is not None:
            # Needed so QuestView.on_timeout() can disable the buttons
            # on this exact message once the 2-minute timeout hits.
            view.message = message
